### ISSUE TITLE
Diagonal elements of the distance matrix are not 0 when w != 1

### ISSUE THREAD

**Issue by VladimirShitov** [fsvbach/WassersteinTSNE#1]
When the parameter `w` (lambda in the original paper) is not equal to 1, the distances of the elements to themselves are not equal to 0. They are quite small but still cause errors when trying to use the distance matrix in other functions (e.g. `scipy.cluster.hierarchy.linkage`). 

Here is the simple code to reproduce this using the toy data provided in the package:

```python
import WassersteinTSNE as WT
import numpy as np
import matplotlib.pyplot as plt

dataset, HGM = WT.ToyDataset()
Gaussians    = WT.Dataset2Gaussians(dataset)
GWD          = WT.GaussianWassersteinDistance(Gaussians)

ws = np.linspace(0, 1)
traces = [np.trace(GWD.matrix(w=w)) for w in ws]

plt.plot(ws, traces)
plt.xlabel("w")
plt.ylabel("Sum of diagonal elements")
```

Result:
![Unknown-132](https://user-images.githubusercontent.com/35199218/214502546-31b4ea9e-808a-448b-8b9e-d3f308683103.png)

I believe, this issue is numeric, and propose setting diagonal elements to 0 before returning the distances matrix. This will help potential users to avoid problems

**Comment by fsvbach** [comment]
Hi Vladimir,

thanks for opening this issue. You are right, this was due to line 98 in Distances.py
`return matrix - matrix.min()`
which I replaced now (after renaming 'matrix' with 'K') by 
`np.fill_diagonal(K, 0)`
`return K`

This solves the problem, so I'm closing this issue.
